### ISSUE TITLE
Adding local storage

### ISSUE THREAD

**Issue by Priyaraj17** [Priyaraj17/CompanyList#18]
Can someone work on adding local storage? If a user checks the checkbox then that should be stored every time he/she opens the web application.

**Comment by nitin094-hub** [comment]
Can I work on this issue?

**Comment by Priyaraj17** [comment]
Yeah sure. Please go ahead.

**Comment by Priyaraj17** [comment]
Hey, Thanks a lot for this. I will be adding an about us page soon. Will mention the names of all the contributors as well. Thanks :)
