### ISSUE TITLE
One unicorn name is wrong

### ISSUE THREAD

**Issue by muskan24r** [Priyaraj17/CompanyList#3]
Please change Incertis to Icertis.

Thanks

**Comment by Priyaraj17** [comment]
Can you do that? You can make a pull request. Shall I assign it to you?

**Comment by zabihhaqqani** [comment]
can I make this pull request? 
you can assign it to me

**Comment by Priyaraj17** [comment]
Sure, go ahead.

**Comment by zabihhaqqani** [comment]
The unicorn name is already changed

![Capture](https://user-images.githubusercontent.com/53895282/164894005-413ad3ab-67ec-4004-a485-e50fbd6e7f5e.JPG)

**Comment by Priyaraj17** [comment]
> The unicorn name is already changed
> 
> ![Capture](https://user-images.githubusercontent.com/53895282/164894005-413ad3ab-67ec-4004-a485-e50fbd6e7f5e.JPG)
> 

Ohh okay. Ummm if you are interested you can add more unicorns as I think a lot of unicorns have been added recently. Thanks

**Comment by zabihhaqqani** [comment]
I have added a few more names and sent a pull request.

**Comment by Priyaraj17** [comment]
Ohh dw... Ignore the checks.

**Comment by zabihhaqqani** [comment]
Okay I have sent the pull request

**Comment by Priyaraj17** [comment]
> Okay I have sent the pull request 

Thanks a lot. Have merged the changes

**Comment by zabihhaqqani** [comment]
This issue can be closed
